[package]
name = "factorial-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.org>"]
edition = "2018"
publish = false

[dependencies.factorial]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.34.0"
path = "../../../../numbat-wasm-debug"
