ls = [
    
    "erd1dp7pytgfmlqkctqftvsr5fqv9vem7u7x3q9cea3uw5ul79d5xeqscn8y6c",
    "moa1dp7pytgfmlqkctqftvsr5fqv9vem7u573y9cea3uw5ul79d5xeqsjvaj39",
    
    "erd1qqqqqqqqqqqqqpgq5400a82at6ttplyrdhyn8kk9lhxaed5d0n4s9s77kz",
    "moa1qqqqqqqqqqqqqpgq5400a82at6ttplyrdhyn8kk9lhxaed5d0n4sggc32j"

    "erd1qqqqqqqqqqqqqpgquu5rsa4ee6l4azz6vdu4hjp8z4p6tt8m0n4suht3dy",
    "moa1qqqqqqqqqqqqqpgquu5rsa4ee664azz6vfu4h3e8z4p6ft8m0n4sszth6l"

    "erd1qqqqqqqqqqqqqpgq4nlkk7jwhqgp4r08lal46tqt70jdv0685u7qrr3l2d",
    "moa1qqqqqqqqqqqqqpgq4nlkk7jwhqgp4r08lal46tqt70jdv0685u7qwmhska",

    "erd1uh67c2lkhyj4vh73akv7jky9sfgvus8awwcj64uju69mmfne5u7q299t7g",
    "moa1uh67c2lkhyj4vc737kv7jkygsfgvus8awwcj6huju69mmfne5u7qtffxsf",

    "erd1qqqqqqqqqqqqqpgqshqmekudxlxwp0d9j368etjamr5dw7k45u7qx40w6h",
    "moa1qqqqqqqqqqqqqpgqscqmekudxlxwp0d9j368etjamr5dw7k45u7qnz0ex6",

    "erd1qqqqqqqqqqqqqpgqllqglpjdrz5kn3m0k9uf9hdqjmg3xdhk6r7se3wvlk",
    "moa1qqqqqqqqqqqqqpgqllqglpjdrz0u83mek9uglhdqjmg3xdhk6r7shecp5v",
    
    "erd1dyxrt6ky32hpvqh9w9kgt262z4c6su65myzy33styw47m9nkrplqrtnc5r",
    "moa1dyxrt6ky32hpvqh9w9k8hg22z4ceuu65myzy30qtyw47m9nkrplq742j45",

    "erd1qqqqqqqqqqqqqpgqju6muu3kj2uqpqwz798g2jeepyn8jwn5rkqsgwvu0x",
    "moa1qqqqqqqqqqqqqpgqju6muu3k3zuqpqwzua88kjeepyc8jwn5rkqs5ypear", 

    "erd1qqqqqqqqqqqqqpgqfzydqmdw7m2vazsp6u5p95yxz76t2p9rd8ss0zp9ts",
    "moa1qqqqqqqqqqqqqpgqfzydqmdyan0d3qqpuy5p95yxz76t2p9rd8ssrfj3yc",

    "erd1spyavw0956vq68xj8y4tenjpq2wd5a9p2c6j8gsz7ztyrnpxrruqzu66jx", # old key
    "erd1w827ezsgdc76dtwlflzpugerv9dcaclcr5khd2yshx9ua92r9fuqppeexw", # new key
    "moa1w827ezsgdc76dtwlflzpugerv9dcaclcr5khd2yshx9ua92r9fuqvelk67" # replaced

    "erd1l453hd0gt5gzdp7czpuall8ggt2dcv5zwmfdf3sd3lguxseux2fsmsgldz",
    "moa1l453hd0gt5gzdp7czpuall8ggt2dcv5zwmfdf3sd3lguxseux2fskgws3j",

    "erd1qqqqqqqqqqqqqpgqcy2wua5cq59y6sxqj2ka3scayh5e5ms7cthqht8xtp",
    "moa189n9gzenf4d5p9x0368e3wsjnytll9ngkr6z8phd08073elhrgldz8xdq6",

    "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
    "moa1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssfq94h8", # generated by rust code 

    "erd1k2s324ww2g0yj38qn2ch2jwctdy8mnfxep94q9arncc6xecg3xaq6mjse8",
    "moa1k2s324ww2g0yj38qn2ch2jwctdy8mnfxep94q9arncc6xecg3xaqhr5l9h",

    "erd1kyaqzaprcdnv4luvanah0gfxzzsnpaygsy6pytrexll2urtd05ts9vegu7",
    "moa1kyaqzaprcdnv4luvanah0gfxzzsnpaygsy6pytrexll2urtd05tsg5l8qw",
    
    "erd18tudnj2z8vjh0339yu3vrkgzz2jpz8mjq0uhgnmklnap6z33qqeszq2yn4",
    "moa18tudnj2z8vjh0339yu3vrkgzz2jpz8mjq0uhgnmklnap6z33qqes0cvt09",

    "erd1kdl46yctawygtwg2k462307dmz2v55c605737dp3zkxh04sct7asqylhyv",
    "moa1kdl46yctawygtwg2k462307dmz2v55c605737dp3zkxh04sct7asdueccu"

    "erd1r69gk66fmedhhcg24g2c5kn2f2a5k4kvpr6jfw67dn2lyydd8cfswy6ede",
    "moa1r69gk66fmedhhcg24g2c5kn2f2a5k4kvpr6jfw67dn2lyydd8cfsruuk3f",

    "erd1dc3yzxxeq69wvf583gw0h67td226gu2ahpk3k50qdgzzym8npltq7ndgha",
    "moa1dc3yzxxeq69wvf583gw0h67td226gu2ahpk3k50qdgzzym8npltqntt8td",

    "erd13x29rvmp4qlgn4emgztd8jgvyzdj0p6vn37tqxas3v9mfhq4dy7shalqrx",
    "moa13x29rvmp4qlgn4emgztd8jgvyzdj0p6vn37tqxas3v9mfhq4dy7s69e0lk"

    "erd1fggp5ru0jhcjrp5rjqyqrnvhr3sz3v2e0fm3ktknvlg7mcyan54qzccnan",
    "moa1fggp5ru0jhcjrp5rjqyqrnvhr3sz3v2e0fm3ktknvlg7mcyan54q0q7upr",

    "erd1z32fx8l6wk9tx4j555sxk28fm0clhr0cl88dpyam9zr7kw0hu7hsx2j524",
    "moa1z32fx8l6wk9tx4j555sxk28fm0clhr0cl88dpyam9zr7kw0hu7hstj5mk9"

    "erd1uv40ahysflse896x4ktnh6ecx43u7cmy9wnxnvcyp7deg299a4sq6vaywa",
    "moa1uv40ahysflse896x4ktnh6ecx43u7cmy9wnxnvcyp7deg299a4sqh5mtjd",

    "erd1932eft30w753xyvme8d49qejgkjc09n5e49w4mwdjtm0neld797su0dlxp",
    "moa1932eft30w753xyvme8d49qejgkjc09n5e49w4mwdjtm0neld797s3hts63",

    "erd1pdv0h3ddqyzlraek02y5rhmjnwwapjyhqm983kfcdfzmr6axqhdsfg4akx",
    "moa1pdv0h3ddqyzlraek02y5rhmjnwwapjyhqm983kfcdfzmr6axqhdsysnj2k",

    "erd1rh5ws22jxm9pe7dtvhfy6j3uttuupkepferdwtmslms5fydtrh5sx3xr8r",
    "moa1rh5ws22jxm9pe7dtvhfy6j3uttuupkepferdwtmslms5fydtrh5stfqvmn"

    "erd1qqqqqqqqqqqqqpgqhn3ae8dpc957t7jadn7kywtg503dy7pnj9ts3umqxx",
    "moa1qqqqqqqqqqqqqpgqhn3ae8dpc957t7jadn7kywtg503dy7pnj9tsuya06k",

    "erd1qqqqqqqqqqqqqpgqyfjjn43spw7teklwtpz4x5waygq2mluyj9ts0mdwn6",
    "moa1qqqqqqqqqqqqqpgqyfjjn43spw7teklwtpz4x5waygq2mluyj9tszrtp02",

    "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u"
]
def checker(tocken, tocken_ls = ls):
    if tocken not in tocken_ls:
        tocken_ls.append(tocken)
        print(f"Tocken added to tocken ls {tocken}")
    else:
        print("Tocken alredy having in ls")

checker("erd1qqqqqqqqqqqqqpgq5400a82at6ttplyrdhyn8kk9lhxaed5d0n4s9s77kz")



