[package]
name = "bonding-curve-contract-meta"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@dharitri.org>"]
edition = "2018"
publish = false

[dependencies.bonding-curve-contract]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.34.0"
path = "../../../../numbat-wasm-debug"
