[package]
name = "pair-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dependencies.order-book-pair]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.34.0"
path = "../../../../../numbat-wasm-debug"
